/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PureButton {
    /**
    * HTML element to use as basis
    */
    'as': string;
    /**
    * Background color
    */
    'color': string;
    /**
    * Is disabled?
    */
    'disabled': boolean;
    /**
    * Displays button as link
    */
    'href': string;
    /**
    * The button or input type (usually submit)
    */
    'type': string;
    /**
    * Optional prop for input to show text
    */
    'value': string;
  }
  interface PureForm {
    /**
    * Makes labels and input elements inline inside groups
    */
    'aligned': boolean;
    /**
    * HTML tag/element for form container
    */
    'as': string;
    /**
    * Stack form elements
    */
    'stacked': boolean;
  }
  interface PureGrid {
    /**
    * HTML tag/element for form container
    */
    'as': string;
  }
}

declare global {


  interface HTMLPureButtonElement extends Components.PureButton, HTMLStencilElement {}
  var HTMLPureButtonElement: {
    prototype: HTMLPureButtonElement;
    new (): HTMLPureButtonElement;
  };

  interface HTMLPureFormElement extends Components.PureForm, HTMLStencilElement {}
  var HTMLPureFormElement: {
    prototype: HTMLPureFormElement;
    new (): HTMLPureFormElement;
  };

  interface HTMLPureGridElement extends Components.PureGrid, HTMLStencilElement {}
  var HTMLPureGridElement: {
    prototype: HTMLPureGridElement;
    new (): HTMLPureGridElement;
  };
  interface HTMLElementTagNameMap {
    'pure-button': HTMLPureButtonElement;
    'pure-form': HTMLPureFormElement;
    'pure-grid': HTMLPureGridElement;
  }
}

declare namespace LocalJSX {
  interface PureButton {
    /**
    * HTML element to use as basis
    */
    'as'?: string;
    /**
    * Background color
    */
    'color'?: string;
    /**
    * Is disabled?
    */
    'disabled'?: boolean;
    /**
    * Displays button as link
    */
    'href'?: string;
    /**
    * The button or input type (usually submit)
    */
    'type'?: string;
    /**
    * Optional prop for input to show text
    */
    'value'?: string;
  }
  interface PureForm {
    /**
    * Makes labels and input elements inline inside groups
    */
    'aligned'?: boolean;
    /**
    * HTML tag/element for form container
    */
    'as'?: string;
    /**
    * Stack form elements
    */
    'stacked'?: boolean;
  }
  interface PureGrid {
    /**
    * HTML tag/element for form container
    */
    'as'?: string;
  }

  interface IntrinsicElements {
    'pure-button': PureButton;
    'pure-form': PureForm;
    'pure-grid': PureGrid;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pure-button': LocalJSX.PureButton & JSXBase.HTMLAttributes<HTMLPureButtonElement>;
      'pure-form': LocalJSX.PureForm & JSXBase.HTMLAttributes<HTMLPureFormElement>;
      'pure-grid': LocalJSX.PureGrid & JSXBase.HTMLAttributes<HTMLPureGridElement>;
    }
  }
}


