/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PureButton {
    /**
    * Background color
    */
    'color': string;
    /**
    * Background color
    */
    'href': boolean;
  }
}

declare global {


  interface HTMLPureButtonElement extends Components.PureButton, HTMLStencilElement {}
  var HTMLPureButtonElement: {
    prototype: HTMLPureButtonElement;
    new (): HTMLPureButtonElement;
  };
  interface HTMLElementTagNameMap {
    'pure-button': HTMLPureButtonElement;
  }
}

declare namespace LocalJSX {
  interface PureButton {
    /**
    * Background color
    */
    'color'?: string;
    /**
    * Background color
    */
    'href'?: boolean;
  }

  interface IntrinsicElements {
    'pure-button': PureButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pure-button': LocalJSX.PureButton & JSXBase.HTMLAttributes<HTMLPureButtonElement>;
    }
  }
}


